version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - spring-boot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 12

  orders_web_app:
    image: orders_web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring-boot-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql:
  oders_web_app:

networks:
  spring-boot-network: